server:
  port: 65203

spring:
  application:
    name: service-a-hoxton
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
        serverAddr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug